#version 450

#include "../lygia/generative/snoise.glsl"

layout (local_size_x = 1024) in;

layout (std430, binding = 0) buffer point_pos_buffer {
  float height[];
};

layout (location = 0) uniform uint buffer_width;
layout (location = 1) uniform float detail;
layout (location = 2) uniform vec2 offset;

void main() {
  uint index = gl_GlobalInvocationID.x;
  if (index != 0)
    index++;

  height[index] = snoise(offset + vec2(index % buffer_width, index / buffer_width));
}
